FROM node:18-alpine

LABEL maintener="Rigoberto Caionda"
LABEL email="rigobertocaionda98@gmail.com"

WORKDIR /app
ENV NODE_ENV=development

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3333
CMD ["node", "ace", "serve", "--watch"]
