services:

  burrinho-backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rigobertocaionda/burrinho-backend:latest
    restart: always

    depends_on:
      mysql4:
        condition: service_healthy
     
    networks:
      - backend

    ports:
      - "3333:3333"
    
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3333
      APP_KEY: ${APP_KEY} # colocar no arquivo .env ou secrets do seu servidor
      DRIVE_DISK: local
      DB_CONNECTION: mysql
      MYSQL_HOST: mysql4
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: qwerty
      MYSQL_DB_NAME: burrinho

      MAIL_MAILER: smtp
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USERNAME: rigobertocaionda98@gmail.com
      SMTP_PASSWORD: drwa gqux kldl loav
      SMTP_FROM_ADDRESS: rigobertocaionda98@gmail.com
      SMTP_FROM_NAME: "Burrinho Game"

  mysql4:
    container_name: "mysql4"

    image: mysql:8.2
  
    healthcheck:
      #test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pqwerty"]
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pqwerty"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

    restart: always
    
    command: --default-authentication-plugin=mysql_native_password

    environment:

      MYSQL_ROOT_PASSWORD: qwerty

      MYSQL_DATABASE: burrinho

    ports:
      - "3306:3306"

    volumes:
      #- $HOME/Docker/data/mysql:/var/lib/mysql
      - mysql_data:/var/lib/mysql

    networks:
      - backend


networks:

  backend:

volumes:
  mysql_data: