services:

  # burrinho-backend é o nome do serviço no docker compose, enquanto que container_name é o nome real do container quando ele estiver up.
  burrinho-backend-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: burrinho-dev

    depends_on:
      mysql4:
        condition: service_healthy
     
    networks:
      - backend

    ports:
      - "3333:3333"
    
    volumes:
    # Permite que as alterações feitas no código reflitam imediatamente no container
    - .:/app
    # Meio que faz um cache do node_modules do host no container. Se no host fizerem um npm install, não reflete aqui, será necessário um novo build da imagem para refletir
    - /app/node_modules
    
    environment:
      NODE_ENV: ${NODE_ENV}
      HOST: ${HOST}
      PORT: ${PORT}
      APP_KEY: ${APP_KEY}
      DRIVE_DISK: ${DRIVE_DISK}
      DB_CONNECTION: ${DB_CONNECTION}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}

      MAIL_MAILER: ${MAIL_MAILER}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM_ADDRESS: ${SMTP_FROM_ADDRESS}
      SMTP_FROM_NAME: ${SMTP_FROM_NAME}

  mysql4:
    container_name: "mysql4"

    image: mysql:8.2
  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

    restart: always
    
    command: --default-authentication-plugin=mysql_native_password

    environment:

      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

      MYSQL_DATABASE: ${MYSQL_DB_NAME}

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - backend


networks:
  backend:

volumes:
  mysql_data: