name: ci-burrinho-game-workflow
on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - develop

jobs:
  # check-application é o ci
  check-application:
    runs-on: ubuntu-latest
    
    steps:
      - name: Cloning the Project
        uses: actions/checkout@v4
      
      - name: Seting Up Node Environment
        uses: actions/setup-node@v4

        with:
          node-version: 20
          # cache npm cachea o node_modules, não precisa baixar o node_modules toda vez que a ci rodar, a não ser que o package.json mudou.
          cache: 'npm'
      
      - name: Installing dependencies
      # npm ci: melhor que npm install em ci
        run: npm ci

      - name: Running Tests
        run: npm test
        # Para rodar os testes, é necessário algumas variáveis de ambiente e podemos passar elas aqui e nos secrets do repositório para não passar diretamente aqui.
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          DRIVE_DISK: ${{ secrets.DRIVE_DISK }}
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_DB_NAME: ${{ secrets.MYSQL_DB_NAME }}
          DB_CONNECTION: mysql

      # Aqui é apenas uma validação para ver se o nosso projeto builda em produção
      - name: Building the Project
        run: node ace build --production --ignore-ts-errors
      
      # Daqui para baixo é configuração do docker e buildar o projeto para ver se vai buildar em produção
      - name: Set QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: rigobertocaionda/burrinho-backend-app:latest
  

  # Aqui começa o processo de cd
  # cd:
  #   needs: check-application
  #   runs-on: ubuntu-latest

  #    # CD não roda em pull_request, apenas roda em merge/push
  #   if: github.ref == 'refs/heads/develop'

  #   steps:
  #     - name: Deploy na VPS (build local)
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.VPS_HOST }}
  #         username: ${{ secrets.VPS_USER }}
  #         password: ${{ secrets.VPS_PASSWORD }}
  #         # O script vai entrar no código com o cd ${{ secrets.VPS_PATH }}, vai puxar o código da develop, vai fazer build da imagem docker e vai reiniciar os servidores
  #         script: |
  #           cd ${{ secrets.VPS_PATH }}

  #           echo "📥 Atualizando código"
  #           git pull origin develop

  #           echo "🐳 Buildando imagem Docker"
  #           docker compose build

  #           echo "🚀 Reiniciando containers"
  #           docker compose down
  #           docker compose up -d